language: csharp
sudo: false
mono:
  - latest
branches:
  except:
    - gh-pages
env:
  global:
    - GH_REPO_NAME: abacus
    - GH_REPO_REF: github.com/sungiant/abacus.git
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz
before_script:
  - ./abacus.sh --nu
  - ./abacus.sh --clean
  - ./abacus.sh --gen
script:
  - ./abacus.sh --build
  - ./abacus.sh --test
after_script:
  - ./abacus.sh --docs
