language:
    cpp

before_install:
    sudo apt-get -y update;

install:
    sudo apt-get -y install mono-complete;

before_script:
    cd scripts;sh generate.sh;cd ../;

script:
    xbuild "build_examples/xs.mono40/Abacus/Abacus (xs.mono40).csproj" /p:Configuration=Release
